// Generated by Tools/Blender/patrol_environment.py; centimetres.
#pragma once
#include "CoreMinimal.h"
namespace HumanityCorridor {
struct FDoor { FVector Hinge, Center; float Yaw, Swing, Width, Height, Thickness; };
inline const FDoor Doors[] = {
    {FVector(-598.500000f, -186.500000f, 0.500000f), FVector(-600.000000f, -240.000000f, 0.000000f), -90.000000f, -100.000000f, 107.000000f, 210.500000f, 5.500000f},
    {FVector(-598.500000f, -1146.500000f, 0.500000f), FVector(-600.000000f, -1200.000000f, 0.000000f), -90.000000f, -100.000000f, 107.000000f, 210.500000f, 5.500000f},
    {FVector(-598.500000f, -1586.500000f, 42.500000f), FVector(-600.000000f, -1640.000000f, 42.000000f), -90.000000f, -100.000000f, 107.000000f, 168.500000f, 5.500000f},
};
struct FPart { const TCHAR* Name; FVector Position, Size; int32 Material; };
inline const FPart Parts[] = {
    {TEXT("Floor"), FVector(-759.000000f, -900.000000f, -6.000000f), FVector(282.000000f, 1836.000000f, 12.000000f), 1},
    {TEXT("Ceiling"), FVector(-759.000000f, -900.000000f, 334.000000f), FVector(282.000000f, 1836.000000f, 12.000000f), 2},
    {TEXT("OuterWall"), FVector(-909.000000f, -900.000000f, 164.000000f), FVector(18.000000f, 1836.000000f, 328.000000f), 0},
    {TEXT("FrontEndWall"), FVector(-759.000000f, 9.000000f, 164.000000f), FVector(282.000000f, 18.000000f, 328.000000f), 0},
    {TEXT("RearEndWall"), FVector(-759.000000f, -1809.000000f, 164.000000f), FVector(282.000000f, 18.000000f, 328.000000f), 0},
    {TEXT("OuterSkirting"), FVector(-898.000000f, -900.000000f, 8.000000f), FVector(4.000000f, 1800.000000f, 16.000000f), 3},
    {TEXT("OuterRail"), FVector(-897.000000f, -900.000000f, 107.000000f), FVector(5.000000f, 1800.000000f, 10.000000f), 3},
    {TEXT("NoticeFrame"), FVector(-894.000000f, -835.000000f, 184.000000f), FVector(8.000000f, 138.000000f, 108.000000f), 5},
    {TEXT("NoticeBoard"), FVector(-888.500000f, -835.000000f, 184.000000f), FVector(4.000000f, 130.000000f, 100.000000f), 4},
    {TEXT("FrontThreshold"), FVector(-609.000000f, -240.000000f, -6.000000f), FVector(22.000000f, 115.000000f, 12.000000f), 1},
    {TEXT("MiddleThreshold"), FVector(-609.000000f, -1200.000000f, -6.000000f), FVector(22.000000f, 115.000000f, 12.000000f), 1},
    {TEXT("RearThreshold"), FVector(-609.000000f, -1640.000000f, 36.000000f), FVector(22.000000f, 115.000000f, 12.000000f), 1},
    {TEXT("RearDoorStepLower"), FVector(-664.000000f, -1640.000000f, 10.500000f), FVector(90.000000f, 110.000000f, 21.000000f), 1},
    {TEXT("RearDoorStepUpper"), FVector(-635.000000f, -1640.000000f, 31.500000f), FVector(32.000000f, 110.000000f, 21.000000f), 1},
    {TEXT("LampHousing0"), FVector(-759.000000f, -225.000000f, 320.000000f), FVector(68.000000f, 125.000000f, 9.000000f), 5},
    {TEXT("LampDiffuser0"), FVector(-759.000000f, -225.000000f, 314.500000f), FVector(58.000000f, 112.000000f, 3.000000f), 6},
    {TEXT("LampHousing1"), FVector(-759.000000f, -650.000000f, 320.000000f), FVector(68.000000f, 125.000000f, 9.000000f), 5},
    {TEXT("LampDiffuser1"), FVector(-759.000000f, -650.000000f, 314.500000f), FVector(58.000000f, 112.000000f, 3.000000f), 6},
    {TEXT("LampHousing2"), FVector(-759.000000f, -1075.000000f, 320.000000f), FVector(68.000000f, 125.000000f, 9.000000f), 5},
    {TEXT("LampDiffuser2"), FVector(-759.000000f, -1075.000000f, 314.500000f), FVector(58.000000f, 112.000000f, 3.000000f), 6},
    {TEXT("LampHousing3"), FVector(-759.000000f, -1500.000000f, 320.000000f), FVector(68.000000f, 125.000000f, 9.000000f), 5},
    {TEXT("LampDiffuser3"), FVector(-759.000000f, -1500.000000f, 314.500000f), FVector(58.000000f, 112.000000f, 3.000000f), 6},
    {TEXT("NoticeSheet0"), FVector(-885.500000f, -880.000000f, 183.000000f), FVector(1.000000f, 32.000000f, 48.000000f), 2},
    {TEXT("NoticeSheet1"), FVector(-885.500000f, -835.000000f, 183.000000f), FVector(1.000000f, 32.000000f, 48.000000f), 2},
    {TEXT("NoticeSheet2"), FVector(-885.500000f, -790.000000f, 183.000000f), FVector(1.000000f, 32.000000f, 48.000000f), 2},
    {TEXT("DoorPlaque0"), FVector(-628.000000f, -240.000000f, 242.000000f), FVector(3.000000f, 94.000000f, 24.000000f), 4},
    {TEXT("DoorPlaque1"), FVector(-628.000000f, -1200.000000f, 242.000000f), FVector(3.000000f, 94.000000f, 24.000000f), 4},
    {TEXT("DoorPlaque2"), FVector(-628.000000f, -1640.000000f, 242.000000f), FVector(3.000000f, 94.000000f, 24.000000f), 4},
};
inline const FLinearColor Colors[] = {
    FLinearColor(0.660000f, 0.700000f, 0.680000f, 1.000000f),
    FLinearColor(0.250000f, 0.290000f, 0.300000f, 1.000000f),
    FLinearColor(0.800000f, 0.820000f, 0.790000f, 1.000000f),
    FLinearColor(0.230000f, 0.290000f, 0.290000f, 1.000000f),
    FLinearColor(0.045000f, 0.130000f, 0.170000f, 1.000000f),
    FLinearColor(0.240000f, 0.280000f, 0.280000f, 1.000000f),
    FLinearColor(0.840000f, 0.930000f, 1.000000f, 1.000000f),
};
inline const FVector Approach(-759, -300, 0);
inline const FVector Inspection(-670, -1200, 0);
}
