// Generated by the Blender runtime exporter. Dimensions in centimetres.
#pragma once
#include "CoreMinimal.h"
struct FHumanityPropDoorSpec { FVector Hinge; FVector StageNormal; float Yaw, Swing, Width, Height, Thickness; };
inline const FHumanityPropDoorSpec HumanityPropDoors[] = {
    { FVector(403.293371f, -1564.391327f, 42.400000f), FVector(-0.897012f, 0.442006f, 0.000000f), -116.231941f, 95.000000f, 95.200000f, 215.200000f, 4.000000f },
    { FVector(-403.293371f, -1564.391327f, 42.400000f), FVector(0.897012f, 0.442006f, 0.000000f), -63.768059f, -95.000000f, 95.200000f, 215.200000f, 4.000000f },
};
