"""
Create a clean, combined Unreal runtime asset from the editable Blender model.

Run:
    blender.exe --background HumanityTrinityRebuild.blend \
        --python Tools/Blender/export_humanity_trinity_rebuild.py

The source .blend is never saved by this script.
"""

from pathlib import Path
import math
import bpy


PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = (
    PROJECT_ROOT
    / "UnrealProject"
    / "Content"
    / "SourceAssets"
    / "HumanityTrinityRebuildEnvironment_Runtime.glb"
)

EXCLUDED_COLLECTION_PREFIXES = (
    "06_Lighting",
    "07_Annotations",
    "99_Cameras",
)


def object_is_excluded(obj):
    if obj.get("runtime_dynamic_prop_door", False):
        return True
    if obj.get("runtime_dynamic_curtain", False):
        return True
    if obj.type in {"LIGHT", "CAMERA"}:
        return True
    for collection in obj.users_collection:
        if collection.name.startswith(EXCLUDED_COLLECTION_PREFIXES):
            return True
    return False


def export_curtain_panel():
    """Unit curtain anchored at its outer lower hem for runtime width animation."""
    nx, nz = 128, 8
    vertices = [(ix/nx, .065*math.cos(ix/nx*16*2*math.pi), iz/nz)
                for iz in range(nz+1) for ix in range(nx+1)]
    faces = []
    for iz in range(nz):
        for ix in range(nx):
            a=iz*(nx+1)+ix
            faces.append((a,a+1,a+nx+2,a+nx+1))
    mesh=bpy.data.meshes.new("SM_CurtainPanel_Mesh")
    mesh.from_pydata(vertices,[],faces); mesh.update()
    uv=mesh.uv_layers.new(name="PhotoUV")
    for poly in mesh.polygons:
        poly.use_smooth=True
        for li in poly.loop_indices:
            co=mesh.vertices[mesh.loops[li].vertex_index].co
            uv.data[li].uv=(co.x*4,co.z*8)
    obj=bpy.data.objects.new("SM_CurtainPanel",mesh)
    bpy.context.scene.collection.objects.link(obj)
    mesh.materials.append(bpy.data.materials["MAT_Curtain_Burgundy"])
    solid=obj.modifiers.new("CurtainThickness","SOLIDIFY"); solid.thickness=.006
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True); bpy.context.view_layer.objects.active=obj
    path=OUTPUT_PATH.parent/"SM_CurtainPanel.glb"
    bpy.ops.export_scene.gltf(filepath=str(path),export_format="GLB",use_selection=True,export_apply=True)
    bpy.data.objects.remove(obj,do_unlink=True)
    print("INTERACTIVE_CURTAIN_EXPORT_COMPLETE",path)


for obj in bpy.context.scene.objects:
    obj.hide_set(False)
    obj.hide_viewport = False
    obj.hide_render = False

export_curtain_panel()

# Generated dimensions keep runtime hinges exactly aligned with Blender holes.
import json
door_specs = json.loads(bpy.context.scene["runtime_prop_doors"])
header = OUTPUT_PATH.parents[2] / "Source" / "HumanityTrinityRebuild" / "HumanityTrinityRebuildDoorLayout.h"
rows = []
for spec in door_specs:
    vector = lambda values: "FVector(" + ", ".join(f"{v:.6f}f" for v in values) + ")"
    rows.append("    { " + vector(spec["hinge"]) + ", " + vector(spec["normal"]) + ", " +
                ", ".join(f"{spec[k]:.6f}f" for k in ("yaw","swing","width","height","thickness")) + " },")
header.write_text("// Generated by the Blender runtime exporter. Dimensions in centimetres.\n#pragma once\n"
    "#include \"CoreMinimal.h\"\n"
    "struct FHumanityPropDoorSpec { FVector Hinge; FVector StageNormal; float Yaw, Swing, Width, Height, Thickness; };\n"
    "inline const FHumanityPropDoorSpec HumanityPropDoors[] = {\n" + "\n".join(rows) + "\n};\n",encoding="utf-8")
print("PROP_DOOR_LAYOUT_EXPORTED", header)

bpy.ops.object.select_all(action="DESELECT")

runtime_objects = []
for obj in list(bpy.context.scene.objects):
    if object_is_excluded(obj):
        continue
    if obj.type in {"MESH", "CURVE", "FONT", "SURFACE"}:
        obj.select_set(True)
        runtime_objects.append(obj)

if not runtime_objects:
    raise RuntimeError("No runtime geometry was found in the source blend file.")

# Convert text/curves and evaluate modifiers before joining.
bpy.context.view_layer.objects.active = runtime_objects[0]
bpy.ops.object.convert(target="MESH")

selected_meshes = [obj for obj in bpy.context.selected_objects if obj.type == "MESH"]
if not selected_meshes:
    raise RuntimeError("Runtime objects could not be converted to meshes.")

floor_candidates = [obj for obj in selected_meshes if obj.name.startswith("Floor_")]
bpy.context.view_layer.objects.active = floor_candidates[0] if floor_candidates else selected_meshes[0]
bpy.ops.object.join()

environment = bpy.context.object
environment.name = "HumanityTrinityRebuildEnvironment_Runtime"
environment.data.name = "HumanityTrinityRebuildEnvironment_Runtime_Mesh"

# Apply transforms so Unreal receives predictable centimeters and a stable pivot.
bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)

dimensions = tuple(round(value, 4) for value in environment.dimensions)
if not (11.0 <= dimensions[0] <= 13.5 and 17.0 <= dimensions[1] <= 19.5):
    raise RuntimeError(f"Unexpected environment bounds in Blender meters: {dimensions}")

OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
bpy.ops.export_scene.gltf(
    filepath=str(OUTPUT_PATH),
    export_format="GLB",
    use_selection=True,
    export_yup=True,
    export_apply=True,
    export_cameras=False,
    export_lights=False,
    export_extras=True,
)

print("=" * 72)
print("UNREAL RUNTIME EXPORT COMPLETE")
print(f"Object: {environment.name}")
print(f"Bounds in Blender meters: {dimensions}")
print(f"Materials: {len(environment.data.materials)}")
print(f"Output: {OUTPUT_PATH}")
print("=" * 72)
