"""Editable fictional corridor and classroom doors for the optional teacher event.

All dimensions below are Unreal centimetres. Blender and C++ use this same source.
Run in an existing reconstruction with --python to update it without rebuilding furniture.
The corridor is gameplay scenery, not a claim about the real school's architecture.
"""
from pathlib import Path
import json
import math
import bpy

ROOT = Path(__file__).resolve().parents[2]
DOORS = [dict(hinge=[-598.5, -y+53.5, .5], yaw=-90., swing=-100.,
              width=107., height=210.5, thickness=5.5, center=[-600., -y, 0.])
         for y in (240., 1200., 1640.)]
# The rear exterior door leads directly to the raised prop-room floor.
DOORS[2]['hinge'][2]=42.5
DOORS[2]['height']=168.5
DOORS[2]['center'][2]=42.
# Material indices: plaster, floor, ceiling, trim, blue noticeboard, metal, emission.
PARTS = [
    ('Floor', [-759, -900, -6], [282, 1836, 12], 1),
    ('Ceiling', [-759, -900, 334], [282, 1836, 12], 2),
    ('OuterWall', [-909, -900, 164], [18, 1836, 328], 0),
    ('FrontEndWall', [-759, 9, 164], [282, 18, 328], 0),
    ('RearEndWall', [-759, -1809, 164], [282, 18, 328], 0),
    ('OuterSkirting', [-898, -900, 8], [4, 1800, 16], 3),
    ('OuterRail', [-897, -900, 107], [5, 1800, 10], 3),
    ('NoticeFrame', [-894, -835, 184], [8, 138, 108], 5),
    ('NoticeBoard', [-888.5, -835, 184], [4, 130, 100], 4),
    ('FrontThreshold', [-609,-240,-6], [22,115,12], 1),
    ('MiddleThreshold', [-609,-1200,-6], [22,115,12], 1),
    ('RearThreshold', [-609,-1640,36], [22,115,12], 1),
    ('RearDoorStepLower', [-664,-1640,10.5], [90,110,21], 1),
    ('RearDoorStepUpper', [-635,-1640,31.5], [32,110,21], 1),
]
for i, y in enumerate((-225, -650, -1075, -1500)):
    PARTS += [(f'LampHousing{i}', [-759, y, 320], [68, 125, 9], 5),
              (f'LampDiffuser{i}', [-759, y, 314.5], [58, 112, 3], 6)]
for i, y in enumerate((-880,-835,-790)):
    PARTS.append((f'NoticeSheet{i}', [-885.5,y,183], [1,32,48], 2))
for i, y in enumerate((-240,-1200,-1640)):
    PARTS.append((f'DoorPlaque{i}', [-628,y,242], [3,94,24], 4))

COLORS = [(.66,.70,.68,1),(.25,.29,.30,1),(.80,.82,.79,1),
          (.23,.29,.29,1),(.045,.13,.17,1),(.24,.28,.28,1),(.84,.93,1,1)]

def write_layout():
    def v(values):
        return 'FVector(' + ', '.join(f'{x:.6f}f' for x in values) + ')'
    lines = ['// Generated by Tools/Blender/patrol_environment.py; centimetres.',
             '#pragma once', '#include "CoreMinimal.h"', 'namespace HumanityCorridor {',
             'struct FDoor { FVector Hinge, Center; float Yaw, Swing, Width, Height, Thickness; };',
             'inline const FDoor Doors[] = {']
    for d in DOORS:
        lines.append('    {'+v(d['hinge'])+', '+v(d['center'])+', '+', '.join(
            f'{d[k]:.6f}f' for k in ('yaw','swing','width','height','thickness'))+'},')
    lines += ['};', 'struct FPart { const TCHAR* Name; FVector Position, Size; int32 Material; };',
              'inline const FPart Parts[] = {']
    lines += ['    {TEXT("'+name+'"), '+v(pos)+', '+v(size)+', '+str(mat)+'},' for name,pos,size,mat in PARTS]
    lines += ['};','inline const FLinearColor Colors[] = {']
    lines += ['    FLinearColor('+', '.join(f'{x:.6f}f' for x in c)+'),' for c in COLORS]
    lines += ['};', 'inline const FVector Approach(-759, -300, 0);',
              'inline const FVector Inspection(-670, -1200, 0);', '}']
    header = ROOT/'UnrealProject/Source/HumanityTrinityRebuild/HumanityTrinityRebuildCorridorLayout.h'
    header.write_text('\n'.join(lines)+'\n',encoding='utf-8')
    return header

def update_scene():
    for obj in list(bpy.data.objects):
        if obj.get('runtime_dynamic_exterior_door') or obj.get('runtime_dynamic_corridor') or (
                obj.name.startswith('Door_0') and '_DoorLeaf_' in obj.name):
            bpy.data.objects.remove(obj,do_unlink=True)
    collection = bpy.data.collections.get('08_Patrol_Corridor_虚构巡查走廊')
    if collection is None:
        collection=bpy.data.collections.new('08_Patrol_Corridor_虚构巡查走廊')
        bpy.context.scene.collection.children.link(collection)
    mats=[]
    for i,c in enumerate(COLORS):
        mat=bpy.data.materials.get(f'MAT_Corridor_{i}') or bpy.data.materials.new(f'MAT_Corridor_{i}')
        mat.diffuse_color=c; mat.use_nodes=True
        p=mat.node_tree.nodes.get('Principled BSDF')
        p.inputs['Base Color'].default_value=c; p.inputs['Roughness'].default_value=.72
        if i==6:
            p.inputs['Emission Color'].default_value=c; p.inputs['Emission Strength'].default_value=3.
        mats.append(mat)
    wood=bpy.data.materials.get('MAT_Door_Wood') or mats[3]
    def box(name,pos,size,mat,flag):
        bpy.ops.mesh.primitive_cube_add(size=1,location=(pos[0]/100,-pos[1]/100,pos[2]/100))
        ob=bpy.context.object; ob.name=name
        ob.dimensions=tuple(x/100 for x in size)
        bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
        for old in list(ob.users_collection): old.objects.unlink(ob)
        collection.objects.link(ob); ob.data.materials.append(mat); ob[flag]=True
        return ob
    for name,pos,size,mat in PARTS:
        box('Corridor_'+name,pos,size,mats[mat],'runtime_dynamic_corridor')
    for i,d in enumerate(DOORS):
        # The leaf's thickness axis is world X; its length follows world Y.
        ob=box(f'Door_0{i+1}_DoorLeaf_Closed',
               [d['hinge'][0],d['hinge'][1]-d['width']/2,d['hinge'][2]+d['height']/2],
               [d['thickness'],d['width'],d['height']],wood,'runtime_dynamic_exterior_door')
        ob['closed_by_default']=True
    bpy.context.scene['runtime_exterior_doors']=json.dumps(DOORS)
    bpy.context.scene['corridor_status']='Fictional optional-gameplay corridor, editable and generated; not surveyed architecture.'
    print('[PATROL_ENVIRONMENT] source_updated doors=3 closed=YES corridor_parts='+str(len(PARTS)))
    print('[PATROL_ENVIRONMENT] layout='+str(write_layout()))

if __name__=='__main__':
    update_scene()
    bpy.ops.wm.save_as_mainfile(filepath=str(ROOT/'HumanityTrinityRebuild.blend'))
    bpy.ops.export_scene.gltf(filepath=str(ROOT/'HumanityTrinityRebuild.glb'),
                              export_format='GLB',export_yup=True,export_cameras=True,export_lights=True,export_extras=True)
    print('[PATROL_ENVIRONMENT] FULL_EDITABLE_ASSEMBLY_GLB_EXPORTED')
